version: "3"
services:
  api:
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    networks:
            webappnetwork
  client:
    container_name: react
    image: react-app
    restart: always
    ports:
        - "3000:3000"
    links:
        - api
    networks:
        webappnetwork
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
            webappnetwork
  networks:
    webappnetwork:
        driver: bridge