version: "3"
services:
    client:
        container_name: client
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        links:
            - api
    api:
        container_name: api
        build: ./api
        restart: always
        ports:
            - "4000:4000"
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        expose:
            - "27017"
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"