version: "3"
services:
    client:
        image: client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
    api:
        image: api
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./api:/api
            - /api/node_modules
        depends_on:
            - mongo
    mongodb:
        image: mongo
        restart: always
        container_name: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"